// angularjs/portfolio/src/app/component/header/header.component.ts
import { Component, Inject } from '@angular/core';

import { APP_CONFIG, AppConfig } from 'src/app/app.config';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
})
export class HeaderComponent {
  angularjs: string = this.config.angularjs;
  reactjs: string = this.config.reactjs;
  django_rest_framework: string = this.config.django_rest_framework;
  expressjs: string = this.config.expressjs;

  EXPRESSJS_URL: string = this.config.EXPRESSJS_URL;
  DJANGO_URL: string = this.config.DJANGO_URL;
  REACTJS_URL: string = this.config.REACTJS_URL;

  constructor(@Inject(APP_CONFIG) public config: AppConfig) {}
}

<nav class="navbar navbar-expand-md navbar-light mb-4 border-bottom">
  <div class="container-fluid">
    <a routerLink="/" class="navbar-brand fw-bold fs-3 text-secondary">
      Feroz's Portfolio
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav fs-5 ms-auto">
        <li class="nav-item mx-2">
          <a routerLink="/" class="nav-link">Home</a>
        </li>
        <li class="nav-item mx-2">
          <a routerLink="/about" class="nav-link">About</a>
        </li>
        <li class="nav-item mx-2">
          <a routerLink="/ci-cd" class="nav-link">CI/CD</a>
        </li>
        <li class="nav-item mx-2">
          <a routerLink="/crud" class="nav-link">CRUD</a>
        </li>
        <li class="nav-item dropdown mx-2">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            >{{ angularjs }}</a
          >
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ REACTJS_URL }}">{{ reactjs }}</a>
            <a class="dropdown-item" href="{{ EXPRESSJS_URL }}"
              >API {{ expressjs }}</a
            >
            <a class="dropdown-item" href="{{ DJANGO_URL }}">{{
              django_rest_framework
            }}</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

// reactjs/portfolio/src/components/header.js
import { Link } from 'react-router-dom';

import { useGlobalState } from './../context/global-context-use.js';

const Header = () => {
  const [templateGlobals] = useGlobalState();
  const { reactjs, angularjs, django_rest_framework, expressjs, title, ANGULARJS_URL, EXPRESSJS_URL, DJANGO_URL } =
    templateGlobals;

  const titleShort = title.split(' ')[0];
  return (
    <>
      <nav className=" navbar navbar-expand-md navbar-light  mb-4 border-bottom">
        <div className="container-fluid ">
          <Link to="/" className="navbar-brand fw-bold fs-3 text-secondary">
            {titleShort}'s Portfolio
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul className="navbar-nav fs-5 ms-auto">
              <li className="nav-item mx-2">
                <Link to="/" className="nav-link">
                  Home
                </Link>
              </li>
              <li className="nav-item mx-2">
                <Link to="/about" className="nav-link">
                  About
                </Link>
              </li>
              <li className="nav-item mx-2">
                <Link to="/ci-cd" className="nav-link">
                  CI/CD
                </Link>
              </li>
              <li className="nav-item mx-2">
                <Link to="/crud" className="nav-link">
                  CRUD
                </Link>
              </li>
              <li className="nav-item dropdown mx-2">
                <a
                  className="nav-link dropdown-toggle"
                  href="/"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  {reactjs}
                </a>
                <div className="dropdown-menu" aria-labelledby="navbarDropdown" style={{ maxWidth: '225px' }}>
                  <a className="dropdown-item" href={ANGULARJS_URL}>
                    {angularjs}
                  </a>
                  <a className="dropdown-item" href={EXPRESSJS_URL}>
                    API {expressjs}
                  </a>
                  <a className="dropdown-item" href={DJANGO_URL}>
                    {django_rest_framework}
                  </a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </>
  );
};

export default Header;
